[application]

# App (Project) Name
name = "apps"
out_dir = "dist"
asset_dir = "public"

[web.app]

# HTML title tag content
title = "apps"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
