name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npx vitest run --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Project
        run: npm run build

      - name: Routes
        shell: bash
        run: |

      - name: Populate service-worker cache
        shell: bash
        run: |
          cd dist

          # create links to index.html for BrowserRouter
          REDIRECTS=(404 $(grep -Po '(?<=path: "\/).+(?=")' ../src/components/Routes/config.tsx))
          for view in ${REDIRECTS[*]}; do cp index.html $view.html; done

          # populating URLS_TO_CACHE in sw.js
          ASSETS=$(find . \( -name 'sw.js' -o -name 'README.md' -o -path './linux' \) -prune -o -type f -print | awk '{print "\"" $0 "\""}' | paste -sd "," -)
          sed -i 's|"__REPLACED_DURING_DEPLOYMENT__"|'${ASSETS}'|' sw.js

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/

  deploy:
    needs: test-and-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
