name: Deploy Dioxus to GitHub Pages

on:
  push:
    branches:
      - dioxus

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true

      - name: Install Dioxus-CLI
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm dioxus-cli

      - uses: Swatinem/rust-cache@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: process CSS files
        run: |
          npm install gulp gulp-if gulp-concat gulp-clean-css gulp-autoprefixer
          npx gulp prod

      - name: Build Project 🎁
        shell: bash
        run: |
          dx build --release
          mv target/dx/apps/release/web/public dist
          REDIRECTS=(404 $(grep -Po '(?<=#\[route\("/)[^:"]+(?="\)\])' src/routes.rs))
          
          cd dist
          for f in ${REDIRECTS[*]}; do cp index.html $f.html; done

          # necessary workaround since I have at least 1 user out there sourcing this
          mv assets/linux .

          # populating URLS_TO_CACHE in sw.js
          ASSETS=$(find assets/ \( -name 'sw.js' -o -name 'README.md' -o -name '*.br' \) -prune -o -type f -print | awk '{print "\"/" $0 "\""}' | paste -sd "," -)
          sed -i 's|"__REPLACED_DURING_DEPLOYMENT__"|'${ASSETS}'|' assets/sw.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
